
package de.bio.hazard.securemessage.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessageWebserviceService", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", wsdlLocation = "http://localhost:8080/messageWebservice?wsdl")
public class MessageWebserviceService
    extends Service
{

    private final static URL MESSAGEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGEWEBSERVICESERVICE_EXCEPTION;
    private final static QName MESSAGEWEBSERVICESERVICE_QNAME = new QName("http://webservice.securemessage.hazard.bio.de/", "MessageWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/messageWebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGEWEBSERVICESERVICE_WSDL_LOCATION = url;
        MESSAGEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public MessageWebserviceService() {
        super(__getWsdlLocation(), MESSAGEWEBSERVICESERVICE_QNAME);
    }

    public MessageWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGEWEBSERVICESERVICE_QNAME, features);
    }

    public MessageWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGEWEBSERVICESERVICE_QNAME);
    }

    public MessageWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGEWEBSERVICESERVICE_QNAME, features);
    }

    public MessageWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessageWebservice
     */
    @WebEndpoint(name = "MessageWebservicePort")
    public MessageWebservice getMessageWebservicePort() {
        return super.getPort(new QName("http://webservice.securemessage.hazard.bio.de/", "MessageWebservicePort"), MessageWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageWebservice
     */
    @WebEndpoint(name = "MessageWebservicePort")
    public MessageWebservice getMessageWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.securemessage.hazard.bio.de/", "MessageWebservicePort"), MessageWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw MESSAGEWEBSERVICESERVICE_EXCEPTION;
        }
        return MESSAGEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
