
package de.bio.hazard.securemessage.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MessageWebservice", targetNamespace = "http://webservice.securemessage.hazard.bio.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MessageWebservice {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addMessage", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", className = "de.bio.hazard.securemessage.webservice.AddMessage")
    @ResponseWrapper(localName = "addMessageResponse", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", className = "de.bio.hazard.securemessage.webservice.AddMessageResponse")
    @Action(input = "http://webservice.securemessage.hazard.bio.de/MessageWebservice/addMessageRequest", output = "http://webservice.securemessage.hazard.bio.de/MessageWebservice/addMessageResponse")
    public void addMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        MessageWebserviceDTO arg0);

}
